// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using TravelConnect.Gta.DataServices;

namespace TravelConnect.React.Migrations
{
    [DbContext(typeof(GtaContext))]
    [Migration("20180117133144_Initiate")]
    partial class Initiate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TravelConnect.Gta.DataModels.City", b =>
                {
                    b.Property<string>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(10)")
                        .HasMaxLength(10);

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("varchar(2)")
                        .HasMaxLength(2);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("Code");

                    b.HasIndex("CountryCode");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("TravelConnect.Gta.DataModels.Country", b =>
                {
                    b.Property<string>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(2)")
                        .HasMaxLength(2);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("Code");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("TravelConnect.Gta.DataModels.Facility", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("varchar(10)")
                        .HasMaxLength(10);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("Code");

                    b.ToTable("Facilities");
                });

            modelBuilder.Entity("TravelConnect.Gta.DataModels.Hotel", b =>
                {
                    b.Property<string>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(15)")
                        .HasMaxLength(15);

                    b.Property<string>("Address1")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Address2")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Address3")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Address4")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("CityCode")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasMaxLength(10);

                    b.Property<string>("Copyright")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Fax")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<float?>("Latitude");

                    b.Property<float?>("Longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<decimal?>("StarRating")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("Code");

                    b.HasIndex("CityCode");

                    b.ToTable("Hotels");
                });

            modelBuilder.Entity("TravelConnect.Gta.DataModels.HotelAreaDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AreaDetail")
                        .IsRequired()
                        .HasColumnType("nvarchar(4000)")
                        .HasMaxLength(4000);

                    b.Property<string>("HotelCode")
                        .IsRequired()
                        .HasColumnType("varchar(15)")
                        .HasMaxLength(15);

                    b.HasKey("Id");

                    b.HasIndex("HotelCode");

                    b.ToTable("HotelAreaDetails");
                });

            modelBuilder.Entity("TravelConnect.Gta.DataModels.HotelFacility", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FacilityCode")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasMaxLength(10);

                    b.Property<string>("HotelCode")
                        .IsRequired()
                        .HasColumnType("varchar(15)")
                        .HasMaxLength(15);

                    b.HasKey("Id");

                    b.HasIndex("FacilityCode");

                    b.HasIndex("HotelCode");

                    b.ToTable("HotelFacilities");
                });

            modelBuilder.Entity("TravelConnect.Gta.DataModels.HotelImageLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Caption")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("HotelCode")
                        .IsRequired()
                        .HasColumnType("varchar(15)")
                        .HasMaxLength(15);

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Thumbnail")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.HasIndex("HotelCode");

                    b.ToTable("HotelImageLinks");
                });

            modelBuilder.Entity("TravelConnect.Gta.DataModels.HotelLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("HotelCode")
                        .IsRequired()
                        .HasColumnType("varchar(15)")
                        .HasMaxLength(15);

                    b.Property<string>("LocationCode")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasMaxLength(10);

                    b.HasKey("Id");

                    b.HasIndex("HotelCode");

                    b.HasIndex("LocationCode");

                    b.ToTable("HotelLocations");
                });

            modelBuilder.Entity("TravelConnect.Gta.DataModels.HotelMapLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("HotelCode")
                        .IsRequired()
                        .HasColumnType("varchar(15)")
                        .HasMaxLength(15);

                    b.Property<string>("MapLink")
                        .IsRequired()
                        .HasColumnType("varchar(4000)")
                        .HasMaxLength(4000);

                    b.HasKey("Id");

                    b.HasIndex("HotelCode");

                    b.ToTable("HotelMapLinks");
                });

            modelBuilder.Entity("TravelConnect.Gta.DataModels.HotelReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("HotelCode")
                        .IsRequired()
                        .HasColumnType("varchar(15)")
                        .HasMaxLength(15);

                    b.Property<string>("Report")
                        .IsRequired()
                        .HasColumnType("nvarchar(4000)")
                        .HasMaxLength(4000);

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30);

                    b.HasKey("Id");

                    b.HasIndex("HotelCode");

                    b.ToTable("HotelReports");
                });

            modelBuilder.Entity("TravelConnect.Gta.DataModels.HotelRoomCategory", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(4000)")
                        .HasMaxLength(4000);

                    b.Property<string>("HotelCode")
                        .IsRequired()
                        .HasColumnType("varchar(15)")
                        .HasMaxLength(15);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.HasIndex("HotelCode");

                    b.ToTable("HotelRoomCategories");
                });

            modelBuilder.Entity("TravelConnect.Gta.DataModels.HotelRoomFacility", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FacilityCode")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasMaxLength(10);

                    b.Property<string>("HotelCode")
                        .IsRequired()
                        .HasColumnType("varchar(15)")
                        .HasMaxLength(15);

                    b.Property<string>("LocationCode");

                    b.HasKey("Id");

                    b.HasIndex("HotelCode");

                    b.HasIndex("LocationCode");

                    b.ToTable("HotelRoomFacilities");
                });

            modelBuilder.Entity("TravelConnect.Gta.DataModels.HotelRoomType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("HotelCode")
                        .IsRequired()
                        .HasColumnType("varchar(15)")
                        .HasMaxLength(15);

                    b.Property<string>("RoomTypeCode")
                        .IsRequired()
                        .HasColumnType("varchar(5)")
                        .HasMaxLength(5);

                    b.HasKey("Id");

                    b.HasIndex("HotelCode");

                    b.HasIndex("RoomTypeCode");

                    b.ToTable("HotelRoomTypes");
                });

            modelBuilder.Entity("TravelConnect.Gta.DataModels.Location", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("varchar(10)")
                        .HasMaxLength(10);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("Code");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("TravelConnect.Gta.DataModels.RoomType", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("varchar(5)")
                        .HasMaxLength(5);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.HasKey("Code");

                    b.ToTable("RoomTypes");
                });

            modelBuilder.Entity("TravelConnect.Gta.DataModels.City", b =>
                {
                    b.HasOne("TravelConnect.Gta.DataModels.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryCode")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TravelConnect.Gta.DataModels.Hotel", b =>
                {
                    b.HasOne("TravelConnect.Gta.DataModels.City", "City")
                        .WithMany("Hotels")
                        .HasForeignKey("CityCode")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TravelConnect.Gta.DataModels.HotelAreaDetail", b =>
                {
                    b.HasOne("TravelConnect.Gta.DataModels.Hotel", "Hotel")
                        .WithMany("HotelAreaDetails")
                        .HasForeignKey("HotelCode")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TravelConnect.Gta.DataModels.HotelFacility", b =>
                {
                    b.HasOne("TravelConnect.Gta.DataModels.Facility", "Facility")
                        .WithMany("HotelFacilities")
                        .HasForeignKey("FacilityCode")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TravelConnect.Gta.DataModels.Hotel", "Hotel")
                        .WithMany("HotelFacilities")
                        .HasForeignKey("HotelCode")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TravelConnect.Gta.DataModels.HotelImageLink", b =>
                {
                    b.HasOne("TravelConnect.Gta.DataModels.Hotel", "Hotel")
                        .WithMany("HotelImageLinks")
                        .HasForeignKey("HotelCode")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TravelConnect.Gta.DataModels.HotelLocation", b =>
                {
                    b.HasOne("TravelConnect.Gta.DataModels.Hotel", "Hotel")
                        .WithMany("HotelLocations")
                        .HasForeignKey("HotelCode")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TravelConnect.Gta.DataModels.Location", "Location")
                        .WithMany("HotelLocations")
                        .HasForeignKey("LocationCode")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TravelConnect.Gta.DataModels.HotelMapLink", b =>
                {
                    b.HasOne("TravelConnect.Gta.DataModels.Hotel", "Hotel")
                        .WithMany("HotelMapLinks")
                        .HasForeignKey("HotelCode")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TravelConnect.Gta.DataModels.HotelReport", b =>
                {
                    b.HasOne("TravelConnect.Gta.DataModels.Hotel", "Hotel")
                        .WithMany("HotelReports")
                        .HasForeignKey("HotelCode")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TravelConnect.Gta.DataModels.HotelRoomCategory", b =>
                {
                    b.HasOne("TravelConnect.Gta.DataModels.Hotel", "Hotel")
                        .WithMany("HotelRoomCategories")
                        .HasForeignKey("HotelCode")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TravelConnect.Gta.DataModels.HotelRoomFacility", b =>
                {
                    b.HasOne("TravelConnect.Gta.DataModels.Hotel", "Hotel")
                        .WithMany("HotelRoomFacilities")
                        .HasForeignKey("HotelCode")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TravelConnect.Gta.DataModels.Facility", "Facility")
                        .WithMany("HotelRoomFacilities")
                        .HasForeignKey("LocationCode");
                });

            modelBuilder.Entity("TravelConnect.Gta.DataModels.HotelRoomType", b =>
                {
                    b.HasOne("TravelConnect.Gta.DataModels.Hotel", "Hotel")
                        .WithMany("HotelRoomTypes")
                        .HasForeignKey("HotelCode")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TravelConnect.Gta.DataModels.RoomType", "RoomType")
                        .WithMany()
                        .HasForeignKey("RoomTypeCode")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
